import { Metadata } from "next";
import { Container } from "@/components/ui/container";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms of Service for ADACheck accessibility scanning service.",
};

export default function TermsPage() {
  return (
    <div className="py-20">
      <Container size="md">
        <article className="prose prose-invert prose-slate max-w-none">
          <h1>Terms of Service</h1>
          <p className="lead">Last updated: January 2025</p>

          <p>
            These Terms of Service (&quot;Terms&quot;) govern your access to and use of ADACheck&apos;s
            website accessibility scanning services, website, and any related software or services
            (collectively, the &quot;Service&quot;). By accessing or using the Service, you agree to be
            bound by these Terms.
          </p>

          <h2>1. Acceptance of Terms</h2>
          <p>
            By creating an account, accessing, or using our Service, you acknowledge that you have
            read, understood, and agree to be bound by these Terms. If you do not agree to these
            Terms, you may not access or use the Service.
          </p>
          <p>
            If you are using the Service on behalf of an organization, you represent and warrant
            that you have the authority to bind that organization to these Terms.
          </p>

          <h2>2. Description of Service</h2>
          <p>
            ADACheck provides automated website accessibility scanning and analysis services.
            Our Service:
          </p>
          <ul>
            <li>Crawls specified web pages to identify potential accessibility issues</li>
            <li>Runs automated checks based on WCAG 2.1 guidelines</li>
            <li>Uses AI to provide explanations and recommendations</li>
            <li>Generates reports in various formats (PDF, JSON)</li>
          </ul>

          <h2>3. Important Disclaimers</h2>
          <h3>3.1 Not Legal Advice</h3>
          <p>
            <strong>THE SERVICE DOES NOT PROVIDE LEGAL ADVICE.</strong> The information and reports
            generated by the Service are for informational purposes only and should not be construed
            as legal advice. Accessibility requirements vary by jurisdiction, industry, and
            circumstances. You should consult with qualified legal counsel regarding your specific
            compliance obligations.
          </p>

          <h3>3.2 No Guarantee of Compliance</h3>
          <p>
            <strong>THE SERVICE DOES NOT GUARANTEE ACCESSIBILITY COMPLIANCE.</strong> Automated
            testing can identify many common accessibility issues but cannot detect all potential
            barriers. Studies suggest automated tools can identify approximately 30-40% of
            accessibility issues. Many WCAG success criteria require human judgment and cannot be
            fully automated.
          </p>

          <h3>3.3 Limitation of Automated Testing</h3>
          <p>
            Our scans are automated and may produce false positives or miss certain issues. Results
            should be verified by qualified accessibility professionals. We strongly recommend
            supplementing automated scanning with:
          </p>
          <ul>
            <li>Manual accessibility testing by trained auditors</li>
            <li>Testing with assistive technologies (screen readers, etc.)</li>
            <li>User testing with people who have disabilities</li>
          </ul>

          <h3>3.4 State-Specific Compliance Information</h3>
          <p>
            <strong>STATE COMPLIANCE ASSESSMENTS ARE FOR INFORMATIONAL PURPOSES ONLY.</strong> When
            you select a state jurisdiction for your scan, we provide general information about
            state accessibility laws and estimated legal exposure. This information:
          </p>
          <ul>
            <li>Is based on publicly available legal information and may not reflect recent changes</li>
            <li>Does not account for all factors that may affect your specific legal situation</li>
            <li>Should not be relied upon as legal advice or a complete legal analysis</li>
            <li>May not reflect local ordinances or industry-specific regulations</li>
          </ul>
          <p>
            State laws vary significantly in their applicability, enforcement, and penalties. The
            risk assessments provided are estimates based on general factors and should be verified
            with qualified legal counsel in your jurisdiction.</p>

          <h2>4. Acceptable Use</h2>
          <p>You agree to use the Service only for lawful purposes and in accordance with these Terms. You agree not to:</p>
          <ul>
            <li>Scan websites you do not own or have authorization to scan</li>
            <li>Use the Service to harm, harass, or interfere with other users or websites</li>
            <li>Attempt to circumvent usage limits or access controls</li>
            <li>Reverse engineer, decompile, or attempt to extract source code</li>
            <li>Use the Service for any illegal or unauthorized purpose</li>
            <li>Transmit viruses, malware, or other harmful code</li>
            <li>Resell or redistribute the Service without authorization</li>
          </ul>

          <h2>5. User Accounts</h2>
          <p>
            You are responsible for maintaining the confidentiality of your account credentials and
            for all activities that occur under your account. You agree to notify us immediately of
            any unauthorized use of your account.
          </p>

          <h2>6. Intellectual Property</h2>
          <p>
            The Service, including its original content, features, and functionality, is owned by
            ADACheck and is protected by international copyright, trademark, patent, trade
            secret, and other intellectual property laws.
          </p>
          <p>
            You retain ownership of any content you provide to the Service (such as website URLs).
            By using the Service, you grant us a limited license to access and analyze your
            specified web pages for the purpose of providing the Service.
          </p>

          <h2>7. Payment and Subscriptions</h2>
          <p>
            Certain features of the Service require payment. By subscribing to a paid plan, you
            agree to pay the applicable fees. Subscriptions automatically renew unless cancelled
            before the renewal date.
          </p>
          <p>
            We reserve the right to change pricing with 30 days notice. Price changes will not
            affect your current billing period.
          </p>

          <h2>8. Limitation of Liability</h2>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, ACCESSIBILITYAI SHALL NOT BE LIABLE FOR ANY
            INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF
            PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA,
            USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM:
          </p>
          <ul>
            <li>Your use or inability to use the Service</li>
            <li>Any unauthorized access to or use of our servers</li>
            <li>Any interruption or cessation of transmission to or from the Service</li>
            <li>Any bugs, viruses, or similar issues transmitted through the Service</li>
            <li>Any errors or omissions in any content</li>
            <li>Any reliance placed on Service outputs or reports</li>
            <li>Any accessibility claims, lawsuits, or regulatory actions</li>
          </ul>

          <h2>9. Indemnification</h2>
          <p>
            You agree to indemnify and hold harmless ADACheck and its officers, directors,
            employees, and agents from any claims, damages, losses, liabilities, and expenses
            (including attorneys&apos; fees) arising from your use of the Service or violation of these
            Terms.
          </p>

          <h2>10. Termination</h2>
          <p>
            We may terminate or suspend your access to the Service immediately, without prior notice
            or liability, for any reason, including breach of these Terms. Upon termination, your
            right to use the Service will immediately cease.
          </p>

          <h2>11. Changes to Terms</h2>
          <p>
            We reserve the right to modify these Terms at any time. We will provide notice of
            material changes by posting the new Terms on this page and updating the &quot;Last updated&quot;
            date. Your continued use of the Service after changes constitutes acceptance of the
            modified Terms.
          </p>

          <h2>12. Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with the laws of the
            State of Delaware, United States, without regard to its conflict of law provisions.
          </p>

          <h2>13. Dispute Resolution</h2>
          <p>
            Any disputes arising from these Terms or the Service shall be resolved through binding
            arbitration in accordance with the American Arbitration Association&apos;s rules. You agree
            to waive any right to a jury trial or to participate in a class action.
          </p>

          <h2>14. Severability</h2>
          <p>
            If any provision of these Terms is found to be unenforceable, the remaining provisions
            will remain in full force and effect.
          </p>

          <h2>15. Contact Information</h2>
          <p>
            For questions about these Terms, please contact us at:
          </p>
          <p>
            Email: legal@adacheck.io
          </p>
        </article>
      </Container>
    </div>
  );
}
